dbt_airflow_bigquery_healthdata:  # Must match "profile" in dbt_project.yml
  outputs:
    dev:
      dataset: airflow_dev_healthcare_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp-secret.json
      location: us-central1
      method: service-account
      priority: interactive
      project: dbt-health-data-project
      threads: 4
      type: bigquery

    prod:
      dataset: airflow_prod_healthcare_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp-secret.json
      location: us-central1
      method: service-account
      priority: interactive
      project: dbt-health-data-project
      threads: 4
      type: bigquery

  target: dev
